### ISSUE TITLE
isnt std::atomic_thread_fence more appropriate ?

### ISSUE THREAD

**Issue by 69736c616d** [jnk0le/Ring-Buffer#1]
Great ring buffer implementation but let me ask that, why you used std::atomic_signal_fence ?

**Comment by jnk0le** [comment]
It's because atomic_thread_fence generates memory barrier instructions that are unnecessary on a single core microcontrollers. We just need to have a release store instruction (index store), ordered after accessing buffers. 

Templating fences for wmo-multi-core systems is in plans.
