### ISSUE TITLE
 Multiple producers, a single consumer situation will produce a crash

### ISSUE THREAD

**Issue by XMatrixXiang** [jnk0le/Ring-Buffer#16]
#include "memory"
#include "thread"
#include "iostream"
#include "RingBuffer.hpp"
#include  "vector"
#include "sstream"

struct ProfileInfo {
    std::string device_id_;
    std::shared_ptr<std::vector<std::tuple<double, double>>> points_;
};

utility::Ringbuffer<std::shared_ptr<ProfileInfo>> buffer_;

void Consumer(void) {
    while (true){

        std::shared_ptr<ProfileInfo> tempPtr;
        const bool readResult = buffer_.remove(tempPtr);
        if (!readResult) {
            continue;
        }
        std::cout << tempPtr->device_id_ << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
    }
}

void Producer() {
    while (true) {

        std::shared_ptr<ProfileInfo> tempPtr =
            std::make_shared<ProfileInfo>();
        std::ostringstream os;
        os << std::this_thread::get_id();  
        tempPtr->device_id_ = os.str();
        const bool insertResult = buffer_.insert(tempPtr);
        std::this_thread::sleep_for(std::chrono::milliseconds(2));

    }
}

int main() {

    std::thread producer1(Producer);
    std::thread producer2(Producer);
    std::thread consumer(Consumer);
    producer1.join();
    producer2.join();
    consumer.join();
    return 0;
}

**Comment by XMatrixXiang** [comment]
![image](https://user-images.githubusercontent.com/13548583/120255849-77d63080-c2bf-11eb-8131-885886bf10db.png)

**Comment by jnk0le** [comment]
Thats expected behaviour from spsc primitives. I should probably remove that misleading example (specific cases and/or mutex should still work though)
