### ISSUE TITLE
Does this ringbuffer thread safe?

### ISSUE THREAD

**Issue by xin-w8023** [jnk0le/Ring-Buffer#20]
Hi, here is a question about data racing.
https://github.com/jnk0le/Ring-Buffer/blob/e93d9afd48c148964323acdef7ec73883f578bbc/ringbuffer.hpp#L352
Assuming we have two threads to write buffer, how do you avoid data racing if two threads writing buffer at the same time ? I don't think the function above could handle the issue.

**Comment by jnk0le** [comment]
it's SPSC only, so it's thread safe only when 1 thread is writing and 1 reading. It can't handle 2 writers.

**Comment by xin-w8023** [comment]
> it's SPSC only, so it's thread safe only when 1 thread is writing and 1 reading. It can't handle 2 writers.

all right, i see. thx for replying.
