### ISSUE TITLE
readBuff(T*, size_t) never actually reads

### ISSUE THREAD

**Issue by zysoft** [jnk0le/Ring-Buffer#3]
Thank you for making this nice implementation! 
I tried to use it in a project and discovered that there is small issue in the implementation of `readBuff(T*, size_t)` — the `head` is used instead of `tail`. This always results in `available` being `0` and thus the read is never performed.

https://github.com/jnk0le/Ring-Buffer/blob/757b4f58c40208a6a8c1702cfc90f87c6963cff3/ringbuffer.hpp#L426

I believe the fix is too small for making a fork, but I can do it if you want.

Thanks!

**Comment by jnk0le** [comment]
Thanks for spotting this.
