### ISSUE TITLE
There is a compiling error in Visual Studio 2015 on Windows 7

### ISSUE THREAD

**Issue by zhengfish** [jnk0le/Ring-Buffer#5]
Hello, jnk0le

While I try to use your ringbuffer.hpp, I got this following compiling error:

`
1>------ Rebuild All started: Project: xxxdump, Configuration: Debug Win32 ------
1>  main.cpp
1> ....................\ringbuffer.hpp(338): error C2675: unary '!': 'const index_t' does not define this operator or a conversion to a type acceptable to the predefined operator
1>   ....................\ringbuffer.hpp(346): note: see reference to class template instantiation 'Ringbuffer<T,buffer_size,wmo_multi_core,cacheline_size,index_t>' being compiled
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========`

**Comment by jnk0le** [comment]
2017 and upwards (v141+) doesn't complain about this kind of construct, so it seems to be a bug in compiler. Anyway, fix is relatively simple.
